name: cw_environment
channels:
- conda-forge
- defaults
dependencies:
- cython
- libgdal=2.2.1
- numpy
- opencv=3.2.0=np113py36_blas_openblas_204
- pip=9.0.1=py36_0
- pyproj
- pytables
- python=3.6.2=0
- python-dateutil=2.6.1=py36_0
- pytz=2017.2=py36_0
- pywavelets=0.5.2=np113py36_0
- pyyaml=3.12=py36_1
- readline=6.2=0
- requests=2.18.4=py36_1
- scikit-image
- scikit-learn
- scipy
- setuptools=36.2.2=py36_0
- six=1.10.0=py36_1
- sortedcontainers=1.5.7=py36_0
- sqlite=3.13.0=1
- tblib=1.3.2=py36_0
- tk=8.5.19=2
- toolz=0.8.2=py36_0
- tornado=4.5.1=py36_0
- urllib3=1.22=py36_0
- wheel=0.29.0=py36_0
- x264=20131217=3
- xerces-c=3.1.4=3
- xz=5.2.3=0
- yaml=0.1.6=0
- zict=0.1.2=py36_0
- zlib=1.2.11=0
- pip:
  - affine==2.1.0
  - boto3==1.4.6
  - botocore==1.6.8
  - click-plugins==1.0.3
  - cligj==0.4.0
  - descartes==1.1.0
  - docutils==0.14
  - fiona==1.7.9.post1
  - geopandas==0.2.1
  - jmespath==0.9.3
  - keras==1.1.0
  - munch==2.2.0
  - pathlib
  - rasterio==1.0a9
  - s3transfer==0.1.10
  - shapely==1.6.0
  - snuggs==1.4.1
  - tables==3.4.2
  - theano==0.9.0
  - tqdm